### ISSUE TITLE
add tables of contents to pages with multiple examples.

### ISSUE THREAD

**Issue by yochannah** [intermine/imjs-docs#2]
Currently, examples in this repo  are all inline in a single block of text, e.g.

```javascript
//how to do a nifty action
do.the(niftyness);

// fetch the shiny thing
fetch.shiny().then(function(){ 
   //stuff
}); 
```

If we break it up to use markdown headings, we can generate a table of contents at the top of the page automatically, using `{:toc}`. You can see an example of this here:
- [code](https://raw.githubusercontent.com/intermine/gsoc/master/project-ideas/2019.md)
- [display on the page](http://intermine.org/gsoc/project-ideas/2019/)

**Comment by er-raoniz** [comment]
I have created indexed structure for some files but, I can't figure out on **how to render table of contents in markdown**. It would be great if you can help me with that! Also, merge the pull requests if they are error-free, so that I successfully complete my Hactoberfest XD! 
Thanks!

**Comment by yochannah** [comment]
Nice one - all merged! Thank you so much and congrats on completing your hacktoberfest PRs! :sparkle:
