### ISSUE TITLE
[easy issue] mark up all code examples as javascript code blocks

### ISSUE THREAD

**Issue by yochannah** [intermine/imjs-docs#4]
In this repository we have several markdown files with examples in code blocks, denoted by three backticks in the code. These examples are all javascript, so it would be nice to enable syntax highlighting by specifying that the examples are javascript. 

example 
```
someJavascriptFunction(function() {
  var thingy = 12;
});
```
vs
```javascript
someJavascriptFunction(function() {
  var thingy = 12;
});
```

**Comment by vilian** [comment]
Hello! What a great opportunity! Can I do it?

**Comment by yochannah** [comment]
Sure, you'd be welcome to! Feel free to ask any questions if you need help
:) whether about the docs themselves, GitHub, or something else.

**Comment by ManosPapaioannou** [comment]
Hello, is this  issue still active, I think it will be a great opportunity for me to start contributing.

**Comment by zdrifted** [comment]
It looks like the issue is still active. Three of the files still need syntax highlighting. I'd like to make a pull request for the Queries.md file. Register.md and User.md would still need highlighting.

**Comment by vilian** [comment]
Go for it! @yochannah is awsome!

**Comment by yochannah** [comment]
hey y'all! Sorry for the delays replying @zdrifted and @ManosPapaioannou, and thanks @vilian for encouraging the others to contribute! :heart_eyes: 

@zdrifted - I've merged your PR, thank you so much! 

@ManosPapaioannou feel free to address some of the pages that still haven't been done, and let me know if you have any questions at all!

P.S. sorry for the delay replying - I was away visiting family! :beach_umbrella: :parasol_on_ground:

**Comment by er-raoniz** [comment]
@yochannah 
Is this issue resolved or still active for PRs?

**Comment by yochannah** [comment]
@er-raoniz - this is definitely open for PRs :) not all codeblocks have the js syntax yet :+1:

**Comment by sianlouisa** [comment]
Hi - newbie contributor here! I'd be happy to take a look at User.md if no one else if currently looking at this :smile:

**Comment by yochannah** [comment]
@sianlouisa Go for it! :rocket: if you have any questions please feel free to ask! If this is your first time making a contribution on GitHub you might want to read this guide on forking first: https://guides.github.com/activities/forking/

**Comment by er-raoniz** [comment]
@yochannah I have addressed the issue in my PR #12  and, probably, all markdowns will have syntax highlighting after the merge. Thank you!

**Comment by yochannah** [comment]
@sianlouisa and @er-raoniz - wow - that was quick, both! Thank you so much :star2:

**Comment by yochannah** [comment]
Looks like all the fiels are done now - thanks all for your help!
