### ISSUE TITLE
Replace rawgit links with links to a non-deprecated CDN

### ISSUE THREAD

**Issue by yochannah** [intermine/imjs-docs#5]
the Getting-Started.md file has some links to [rawgit](https://rawgit.com/) - but rawgit is deprecated and will be discontinued, possibly as soon as October 2019. We should use a different CDN link instead - the rawgit homepage has several suggestions.

**Comment by er-raoniz** [comment]
@yochannah  Does the PR have issue in merge? Should I open a new PR?

**Comment by yochannah** [comment]
fixed by #8  :+1:
